### ISSUE TITLE
Set all new posts to unsolved

### ISSUE THREAD

**Issue by bakerboy448** [bakerboy448/arrsubreddit#1]
```
#017 - Set all new posts to unsolved1 flair
type: submission
set_flair: 
    #["unsolved","347a72ac-d515-11e1-ace2-12313d051e91"]
    css_class: notsolvedcase
    template_id: 347a72ac-d515-11e1-ace2-12313d051e91
```

Need to tweak, but this is the base code
