### ISSUE TITLE
Change to Waiting on OP after a comment

### ISSUE THREAD

**Issue by bakerboy448** [bakerboy448/arrsubreddit#2]
```
#018 - Switch to waiting on OP when someone else comments
type: comment
is_top_level: true            # Only trigger on top-level comments
moderators_exempt: false
author:
    is_submitter: false
    ~name: AutoModerator
action_reason: "018 - Changed flair to unsolved again"
parent_submission:
    flair_css_class (full-exact): "unsolved1"    # Default unsolved flair
    set_flair: 
        css_class: waitingonop
        template_id: fb6ebbf6-05f3-11e3-9e5e-12313d21c6e5
    overwrite_flair: true
```
