### ISSUE TITLE
ER: Change Back to Unsolved after OP replies

### ISSUE THREAD

**Issue by bakerboy448** [bakerboy448/arrsubreddit#3]
```
#019 - Switch from unsolved 1 to 2, so exempt from Automod second scan
type: comment
is_top_level: false        # Should only activate for replies, not top levels
moderators_exempt: false
author:
    is_submitter: true
    ~name: AutoModerator
action_reason: "019 - Changed flair to Waiting"
parent_submission:
    flair_css_class (full-exact): "waitingonop"    # Empty flair
    set_flair: 
        css_class: "unsolved2"
        template_id: 9d157000-a29e-11ea-b1e3-0e2704c7c361
    overwrite_flair: true
```
