### ISSUE TITLE
Better !solved handling

### ISSUE THREAD

**Issue by bakerboy448** [bakerboy448/arrsubreddit#6]
```
#012 - Switch to solved flair on Clippy response
type: comment
priority: 99
author:
    is_submitter: false
    name: "Clippy_Office_Asst"
body (starts-with): "You have awarded 1 point to "
is_top_level: false        # Should only activate for replies, not top levels
moderators_exempt: false
parent_submission:
    flair_template_id:
        - 347a72ac-d515-11e1-ace2-12313d051e91 # unsolved1
        - 9d157000-a29e-11ea-b1e3-0e2704c7c361 # unsolved2
        - fb6ebbf6-05f3-11e3-9e5e-12313d21c6e5 # waitingonop
        - 2ba72878-d515-11e1-821b-12313d051e91 # solved - dark green
    overwrite_flair: true 
    set_flair:         
        template_id: e42fc440-9e13-11e8-b838-0e6f8ba7118e
        css_class: solvedpoint

```
